server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: "/gleamy"
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

logging:
  level:
    org:
      springframework:
        web: "DEBUG"

gleamy:
  root: ${GLEAMY_ROOT}